name: Bug Report
description: Report a bug to help us improve ft_transcendence
title: "[Bug]: "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
        Please fill out the information below so we can reproduce and fix it.

  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: A short description of the bug
      placeholder: "The paddle freezes when a player joins late..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: What steps lead to the issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "The paddle should move smoothly even if..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Instead, the paddle stops and the score doesn't update..."
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser(s) Affected
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      description: If applicable, add screenshots or a short video.
      placeholder: "Drag & drop files here"

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Add any other relevant environment details.
      placeholder: |
        - OS: Ubuntu 22.04
        - Docker version: 24.0.5
        - Node version: 20.x
